

server:
  tomcat:
    uri-encoding: UTF-8



wx:
  appid: wx53d0f9e697163f5c
  secret: 3aa31e8b045729dd457abc849a86335f

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:


  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_repair
    username: root
    password: root




